---
# tasks file for roles/ovpn

- name: Set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: yes

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install packages OpenVPN
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - easy-rsa

- name: Copy Certificates
  copy:
    src: keys/{{ item }}
    dest: /etc/openvpn/server/keys/
    mode: 0600
  with_items:
    ['ca.crt','ta.key','dh.pem','vpnserver.crt','vpnserver.key']

- name: 'Copy Certificates'
  copy:
    src: keys/crl.pem
    dest: /etc/openvpn/server/keys
    mode: 0777 

- name: Create logs
  file:
    path: /var/log/openvpn
    state: directory 

- name: Copy server-ovpn from template
  template:
    src: server-ovpn.j2
    dest: /etc/openvpn/server/server.conf
  notify: start openvpn-server@server









  
- name: Create iptables NAT chain
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: 'eth0'
    jump: MASQUERADE
    protocol: 'all'
    state: present
  notify: save iptables

- name: Auto start iptables NAT
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '^/sbin/iptables-restore'
    line: /sbin/iptables-restore < /etc/sysconfig/iptables
    mode: '+x'
