---
# tasks file for roles/ovpn

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Configuration OVPN Server
  include_tasks: vpn-server.yml
  when: ansible_hostname == "vpn-server"

- name: Configuration OVPN Client
  include_tasks: vpn-client.yml
  when: ansible_hostname == "vpn-client"

- name: Configuration OVPN Client
  include_tasks: clien_pc.yml
  when: ansible_hostname == "pc1" or ansible_hostname == "pc2"
