---
# tasks file for roles/site_to_site

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: Server OpenVPN
  include_tasks: vpn-server.yml
  when: (ansible_hostname == 'vpn-server')

- name: Client OpenVPN
  include_tasks: vpn-client.yml
  when: (ansible_hostname == 'vpn-client')

- name: Install package
  include_tasks: clien_pc1.yml
  when: (ansible_hostname == 'pc1')

- name: Install package
  include_tasks: clien_pc2.yml
  when: (ansible_hostname == 'pc2')
