# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end

  config.vm.define "pc1" do |pc1|
    pc1.vm.network "private_network", ip: "192.168.1.20", virtualbox__intnet: "lan-1"
    pc1.vm.hostname = "pc1"
    pc1.vm.provider "virtualbox" do |v|
      v.name = "pc1"
    end
  end

  config.vm.define "server-ovpn" do |server|
    server.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "lan-1"
    server.vm.network "private_network", ip: "172.20.1.10"
    server.vm.hostname = "server-ovpn"
    server.vm.provider "virtualbox" do |v|
      v.name = "server-ovpn"
      v.memory = 1024
    end
  end

  config.vm.define "client-ovpn" do |client|
    client.vm.network "private_network", ip: "192.168.2.10", virtualbox__intnet: "lan-2"
    client.vm.network "private_network", ip: "172.20.2.10"
    client.vm.hostname = "client-ovpn"
    client.vm.provider "virtualbox" do |v|
      v.name = "client-ovpn"
      v.memory = 1024
    end
  end

  config.vm.define "pc2" do |pc2|
    pc2.vm.network "private_network", ip: "192.168.2.20", virtualbox__intnet: "lan-2"
    pc2.vm.hostname = "pc2"
    pc2.vm.provider "virtualbox" do |v|
      v.name = "pc2"
    end
  end

#  config.vm.provision "site_to_site", type:'site_to_site' do |server|
#    server.inventory_path = 'inventory'
#    server.playbook = 'site_to_site.yml'
#  end

end
